### ISSUE TITLE
Optimized Range Check Gadget

### ISSUE THREAD

**Issue by sshravan** [Zokrates/ZoKrates#1049]
## Abstract

It would be great if ZoKrates can support an optimized range check gadget. Currently, ZoKrates uses the range check algorithm from the Sapling ([Pg 141 Section A.3.2.2](https://github.com/zcash/zips/blob/master/protocol/sapling.pdf)). To check if  ```x < constant```, it ZoKrates takes around 525+ constraints. But if I am not wrong, given the bit representation of x as a witness (bits of x doesn't have to be boolean constrained according to the sapling spec), it would be possible to range check with at most ```2*log2(constant)``` constraints.

## Motivation

Performing ```x < constant``` is costly especially for smaller constants. However, given the bit representation of `x` this can be made substantially cheaper using the range check from sapling. In certain scenarios, it may not be unreasonable to expect that bits of `x` is available. 

## Specification
Let `c` be a compile time const and `n` be the bitlength of `c`.

`range_check(const field c, field x, field[n] x_bits) -> bool`

**Comment by Schaeff** [comment]
I looked more closely at this and will write down what I found:
- we use an adapted version of the Sapling algorithm, the main reason being that in our case, `x < c` is not necessarily being asserted, it can also be used as a boolean value in the program. This means that we are more limited in what we can do, because we cannot just throw (have an unsatisfied constraint) if `x < c` is false.
- there are some optimisations that apply to the general case, for example checking the bits cache for `x` instead of reducing it
- other optimisations require targeting specifically cases where `x < c` is in an assertion, and applying exactly the Sapling algorithm.
