### ISSUE TITLE
Invalid standard library source path while compiling

### ISSUE THREAD

**Issue by Jjjpan** [Zokrates/ZoKrates#1051]
Start with the test example of root.zok, failed with the error message:
Invalid standard library source path: ~/.zokrates/stdlib

**Comment by dark64** [comment]
Did you install ZoKrates using our onliner script? You need to have a working standard library path for compilation to be successful. By default, ZoKrates tries to find the standard library in `~/.zokrates/stdlib`, otherwise you have 2 options:
* Set the `ZOKRATES_STDLIB` environment variable with a working standard library path
* Providing the path using `--stdlib-path` flag (eg. `zokrates compile -i root.zok --stdlib-path <path_to_stdlib>`)
