### ISSUE TITLE
ERRORS

### ISSUE THREAD

**Issue by ox0sara** [Zokrates/ZoKrates#1362]
## Environment

- Compiler version:
- Operating system:

**Comment by dark64** [comment]
@0x0sara Can you elaborate more on the errors you are getting? Judging by your other open issues it seems like you are trying to compile old zokrates code using the newer compiler. This won't work as we changed the syntax since [0.8.0](https://github.com/Zokrates/ZoKrates/releases). Free free to reopen the issue if you have any other questions.

**Comment by ox0sara** [comment]
Thanks I've change my code, But I hope ZoKrates improve its documentation especially integration with  frontend libraries such as next.js and resct.js to make it more usable.
