### ISSUE TITLE
Remove build from dev Docker

### ISSUE THREAD

**Issue by Schaeff** [Zokrates/ZoKrates#165]
I'm posting this to collect a bit of feedback before I submit a PR.
Now that we have a Dockerfile for production (optimised for size) and a dev one (including the Rust toolchain, etc), I'm thinking we could remove `./build.sh` from the dev one. When I use it, I generally mount my local repo and do not necessarily want to build zokrates when the docker image builds (this takes time), and rather want to build it manually inside the container.

Any thoughts on this @fleupold @JacobEberhardt @stefandeml ? Do you use the dev Docker at all? Do you care?

Thanks!

**Comment by fleupold** [comment]
I do use Docker and I usually don't change ZoKrates code before running it (therefore an initial build makes sense for me). 

I can kick off a build first thing when I enter the container, that's not a big deal, but I wonder if we could use something like docker-compose and provide different services (one that does run the build command on entry and one doesn't). 
Docker compose also makes it easy to specify mounts as a default (rather than providing them as part of docker run).

**Comment by stefandeml** [comment]
Yeah, docker compose would be nice.

I stopped using the Dev Docker because it's too annoying to deal with the mounts (provide them during start, support for multiple mounts, general performance,..). So from my point of view you can remove the zokrates build.

**Comment by Schaeff** [comment]
It's gone 💀
