### ISSUE TITLE
Add more details to compile time errors

### ISSUE THREAD

**Issue by stefandeml** [Zokrates/ZoKrates#217]
It would be great to have more details on compile time errors like:

* function name ("stack trace")
* line-number

@JacobEberhardt is this something we can get easily with the new parser?

**Comment by JacobEberhardt** [comment]
This is not parsing related in my opinion, hence the new parser would not solve this.

Basically, the required information is available now. The key problem is that during the flattening step, all function calls are resolved into one constraint system. Currently, the meta-information which function (or more precisely, which function invocation) a set of constraints in this large constraint system belongs to, is not kept track of.
However, this is certainly desirable and something that we could add.

**Comment by stefandeml** [comment]
Ok, makes sense.
Syntax errors however should be easy to add I assume?

**Comment by JacobEberhardt** [comment]
Yes, the vast majority of these should be caught in parsing and proper handling will happen there.

**Comment by Schaeff** [comment]
@JacobEberhardt to be precise:
- all compile time errors should be caught before flattening, anything after that assumes that the program is correct and any errors would be internal compiler errors which is not what we're looking at here. I guess you're talking about the semantic checker here which should have source information 👍 
- Adding {file for syntax errors, line number and file for semantic errors} is feasible, if that's sufficient here let's add issues for exactly these two things
- Something else that might be outside of this scope is being able to catch all errors in a program instead of the first one only. @stefandeml any thoughts?
