### ISSUE TITLE
Need to support implicit definition of functions

### ISSUE THREAD

**Issue by wushuang83git** [Zokrates/ZoKrates#291]
Now Zokrates only supports explicit definition of functions, which means you have to define exactly how the output value is calculated from the input value step by step.
In some cases, it could cost much less constraints if we use implicit definition of functions. There also exists extreme cases where an explicit definition of function is not possible for Zokrates now. For example, for a function F(x):

F(x) = 0, if x=0;
F(x) = 1/x, otherwise

If you want to implement this function in Zokrates, you need to calculate the value of 1/x first and use something like an if statement to choose between 0 and 1/x. But if x=0, 1/x cannot be calculated. However, this function y=F(x) can be defined using an implicit function:

x*y = b
b*b = b (xy is either 0 or 1)
(b+1)(x-y)=0 (if xy is 0 then x=y )
Note: this is first proposed here: https://github.com/zcash/zcash/issues/2233#issuecomment-442096749

But in an implicit definition, it may not be clear how the output value could be calculated from the input value, which could lead to problem when generating the witness value.

So, in order to support implicit function in Zokrates, we need at least two features:
1. Method to define implicit relation between input and output
2. Alternative way to calculate output value from input value explicitly for the defined implicit function above in order to generate its witness value automatically.

**Comment by Schaeff** [comment]
Thanks for this. 1. is already available with constraint statements (using `a == b`).We've been thinking about user-defined witness generation (your 2.) but this won't be out in the short term.

We added `x != 0` as a constraint when doing `y = 1/x` inversion because otherwise y is unconstrained, which is not what people want in general, see page 16 [here](https://github.com/daira/zcon0/blob/master/zkproofs.pdf)

What we could do is provide a function `div_unchecked(field x) -> (bool, field)` which returns (x == 0, 1 / x) where 1/x is unchecked, ie it returns an arbitrary value if x == 0. Then it's the user's responsibility to check and only use 1/x if x != 0.

cc @stefandeml

**Comment by Schaeff** [comment]
Closing this as we have #135
