### ISSUE TITLE
Rename Source Code File Ending .code -> .zok

### ISSUE THREAD

**Issue by JacobEberhardt** [Zokrates/ZoKrates#392]
The `.code` file extension is generic and users asked for a change.
I propose to change the file ending to `.zok`

Before that, we should remove file extensions from import statements.

**Comment by JacobEberhardt** [comment]
We decided the following:
- ZoKrates code file endings will be renamed from `.code` to `.zok`
- The human-readable output will be renamed from `.code` to `.ztf` for ZoKrates Text Format.
- The binary-output the compiler generates remains without file ending.

Implementation will happen in two steps:
1. Remove file endings in import-statements. A module to be imported is specified by its name and must not have a file extension. The `.zok` extension should be added internally when evaluating imports before passing to the filesystem resolver.
2. Rename all files to have the new file ending `.zok`. Change the cli to support the new file endings `.zok`and `.ztf`.

**Comment by Schaeff** [comment]
Strictly speaking, step 1 could add `.code` so that no file changes are needed, only import statements. Then step 2 is changing the extension to `.zok`.

**Comment by fulldecent** [comment]
Regarding the input and output of compiling, these will now both be `.zok`, correct? The compiling step is just putting the .zok into a canonical form.

Regarding imports, I request that for now the full file name be used. There is at least one higher-level tool that is compiling down to .zok format.

See: https://github.com/EYBlockchain/zokrates-preprocessor (project is not production ready, and works with outdated .zok format).

That project has `.pcode` which can import other `.pcode` and `.code` files. It would be too confusing if the files are specified in an include without a file ending.

**Comment by Schaeff** [comment]
Thanks for your comment!

> Regarding the input and output of compiling, these will now both be .zok, correct? The compiling step is just putting the .zok into a canonical form.

No because as of now the human-readable output of the compile (`.code`) is not valid ZoKrates source, hence `.ztf`. It's only for debugging purposes. The binary `out` will stay without extension for now.

> Regarding imports, I request that for now the full file name be used. There is at least one higher-level tool that is compiling down to .zok format.

We could make the file extension optional in the short term, defaulting to `.zok` if not provided. Also, these alternative extension names were introduced because of limitations of the ZoKrates language, fixed with another DSL on top. We're working towards making these preprocessors obsolete by making the language more powerful.

Also, I suspect a .pcode is compiled to a .code file, at which point the imports can be advjusted to point at the .code file. So this could be fixed in the preprocessor, by making the removal of `.pcode` extensions part of preprocessing.

**Comment by iAmMichaelConnor** [comment]
@fulldecent @Schaeff we're moving towards 'removing' the `.pcode` files from nightfall.

They were initially a way of writing more succinct code which was less prone to errors. Because Nightfall still uses sha256 within its proofs, there's a lot of binary manipulation, and so `.code` syntax was unwieldy (hundreds of lines of repeated code for a Merkle inclusion proof). The addition of arrays to zokrates' syntax has helped reduce our .code files now. Although bit manipulation is still a bit tricky (see  #477 for why 2-d arrays would be useful), we're going to remove the extra layer of transpiling (i.e. remove .pcode) from Nightfall.

Therefore, (hopefully in the next couple of weeks), we'll be fine to migrate over to .zok (with a lot of find+replace in our repo).

**Comment by JacobEberhardt** [comment]
Closing as it is merged by now.
