### ISSUE TITLE
Why libsnark is removed by default from 0.4.4?

### ISSUE THREAD

**Issue by BlockHeader** [Zokrates/ZoKrates#449]
From 0.4.4, Bellman is integrated, and Libsnark is removed. I want to double-check about the purpose.  EC calculation Performance? Programing Language, Rust vs. C++? Integration efforts? Portable? 
Thanks :)

**Comment by Schaeff** [comment]
The reason is that the build system for libsnark was holding us back to have binaries on different platforms.

You're free to build ZoKrates yourself if you're on Linux with libsnark enabled, and we would of course welcome contributions to make libsnark reliably build on many platforms as it is not our focus at this point.
