### ISSUE TITLE
Introduce a syntactic sugar to define constants

### ISSUE THREAD

**Issue by dark64** [Zokrates/ZoKrates#778]
We should introduce some kind of syntactic sugar to provide a way to define global constants

```
const EXAMPLE_CONST 0xDEADBEEF
```

I'm not sure if this syntax fits the language best, so we should discuss this further.

**Comment by Schaeff** [comment]
One thought I had is that since functions are pure, argument-less functions are constant. This means that we could even allow constant "blocks" which in the background are just treated the same way argument-less functions are today. Similar to the `lazy_static` macro in Rust. Maybe we don't need this right now, but I think the design we choose for this should keep that in mind.

Rust has `const THING: u32 = 0xABAD1DEA;` which I guess for us could look like `const u32 THING = 0xABAD1DEA`

**Comment by dark64** [comment]
> One thought I had is that since functions are pure, argument-less functions are constant. This means that we could even allow constant "blocks" which in the background are just treated the same way argument-less functions are today. Similar to the `lazy_static` macro in Rust. Maybe we don't need this right now, but I think the design we choose for this should keep that in mind.
> 
> Rust has `const THING: u32 = 0xABAD1DEA;` which I guess for us could look like `const u32 THING = 0xABAD1DEA`

My first idea was to just have named constants where a name is defined to be used instead of a literal constant, but I agree we should expand this further at some point. I think your example is good of a start on this.
