### ISSUE TITLE
CLI verify always passes

### ISSUE THREAD

**Issue by markspanbroek** [Zokrates/ZoKrates#995]
## Description

Going through the [Hello Zokrates!](https://zokrates.github.io/gettingstarted.html#hello-zokrates) example, I noticed that no matter what values I supply in the `compute-witness` step, the `verify` step will always print `PASSED`.

I expected the `verify` step to only print `PASSED` when I supply a valid square root in the `compute-witness` step.

## Environment

- Compiler version: rustc 1.53.0-nightly (42816d61e 2021-04-24)
- Operating system: Debian Linux

I tried latest develop compiled from sources, and the one-line installation of 0.7.6. Both gave the same results.

## Steps to Reproduce

Take the `root.zok` from the example:
```zok
def main(private field a, field b) -> bool:
  return a * a == b
```

Then run the steps from the example, but supply invalid inputs:
```bash
zokrates compile -i root.zok
zokrates setup
zokrates compute-witness -a 337 1234
zokrates generate-proof
zokrates verify
```

See that the verify step outputs:
```
Performing verification...
PASSED
```

**Comment by dark64** [comment]
You might be confusing the program returning true/false and the proof being invalid/valid. Proofs generated by ZoKrates are always valid (the verifier returns always true), you'd need to fiddle with the proof to make it invalid (try to change some value in `proof.json` and run the verification again).

You are not generating a proof that the program resulted in a "true" value, you are generating a proof that you have run the computation (ie. verifiable computation). In other words, you can generate a valid proof that proves you have run the computation that resulted in a "false" value. That is why you get a "PASSED" result from the verify command.

This can be confusing because the example returns a logical value (a boolean), but you can write a program that returns something else, for example, a hash. In this case, a verifier wants to verify that the prover executed the program with his or her private data (a preimage of the hash) presented by the witness, which he or she used to generate the proof. The verifier can then verify this proof, which proves that the prover actually executed this code and obtained these results. If you want to check for a certain value, you can assert in your program like so:

```zok
def main(private field a, field b):
  assert(a * a == b)
  return
```

This way you wouldn't be able to compute the witness and generate the proof if the assert fails. Hope this helps.

**Comment by markspanbroek** [comment]
That was exactly my confusion. Thank you so much for clearing this up for a ZoKrates newbie like me :)
